services:
  api:
    build: 
      context: ./api
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "5000:5000"
    env_file:
      - .env
    networks:
      - backend
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    env_file:
      - .env
    networks:
      - backend

networks:
  backend:
    driver: bridge